### ISSUE TITLE
Scheduler should support multiple Scheduler and Score in different namespace

### ISSUE THREAD

**Issue by nkwangleiGIT** [kube-arbiter/arbiter#108]
We should support to have multiple scheduler & score in different namespace, and the pod to be scheduled should use the scheduler&score under its namespace first. If it doesn't exist, we can fallback to use the system scheduler&score under kube-system namespace. 
In this approach, we can support to use difference schedule policy under different namespace for better control.
User scenarios:

1. One deployment under namespace ns-a has 3 replicas, and one of them have issue on node-1, we what to move this pod to node-2. But don't want to add nodeSelector/nodeAffinity in the deployment(as it'll restart all pods). Another is to use injector(but it's not convenient). So we can add logic to Score under its namespace and let the pod having specified labels to scheduled to the nodes. Something like below in the Score:
```
if (pod.raw.metadata.labels['app'] == 'test-busybox' && node.raw.metadata.name == 'node-1'){
  console.log("Matched ...");
  return 1;
} else {
  return 0;
}
```

BTW: can we add some events to Score CR, so we can know which pod was scheduled to which node using this score?

**Comment by Abirdcfly** [comment]
Update idea:
1. we can only use Score CR.
2. Score should Add weight filed in Spec. When scheduling a pod, first look for all Score CR in pod's namespace. If we can't find them, then look for all Score CR under `kube-system` namespace, execute these JS separately, and get the final weighted scheduling score according to the weight of Score to complete the scheduling.
