### ISSUE TITLE
Tunable controller options, and context aware logger :tada::tada::tada::tada::tada:

### ISSUE THREAD

**Issue by tedli** [kube-arbiter/arbiter#7]
Code of the initial commit, contains using of `klog` directly, which is not a best practice when implementing controller using `controller-runtime`.

The controller runtime provides a context aware logging mechanism. It logs the context (resource name and namespace), and in a message plus parameter style. So we can search the message, to locate the code, and know the context through the parameter. Since log is not UI, format string can provide readable content, but it's not friendly for debugging.

Furthermore, the context logging is a wrapper, it supports numerous backend like `klog`, `zap`, etc. When use with klog, it can consume the `-v` option, so the  V could not only affect with our code, but also affect with the controller runtime itself.

Introduce a plugin like command line flag parsing mechanism, can help to define some module specific command line argument, in this way, we not need to define the command line argument in `main.go` or somewhere far away from the module logic code.

**Comment by nkwangleiGIT** [comment]
Thanks for your suggestion and contribution
